In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original:", arr)
print("Reversed:", arr[::-1])

Original: [1 2 3 6 4 5]
Reversed: [5 4 6 3 2 1]


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# flatten()
print("Flatten (method 1):", array1.flatten())

# ravel()
print("Flatten (method 2):", array1.ravel())

Flatten (method 1): [1 2 3 2 4 5 1 2 3]
Flatten (method 2): [1 2 3 2 4 5 1 2 3]


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print( np.array_equal(arr1, arr2))

True


In [7]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = counts.max()
    most_freq = values[counts == max_count]
    indices = np.where(np.isin(arr, most_freq))[0]
    return most_freq, indices

print("x", most_frequent(x))
print("y", most_frequent(y))

x (array([1]), array([0, 5, 7, 8, 9]))
y (array([1, 3]), array([0, 1, 2, 4, 8, 9]))


In [11]:
m = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all elements:", m.sum())
print("Row-wise sum:", m.sum(axis=1))
print("Column-wise sum:", m.sum(axis=0))

Sum of all elements: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [10]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Diagonal sum
print("Diagonal sum:", np.trace(n_array))
# ii & iii. Eigenvalues, Eigenvectors
eigvals, eigvecs = np.linalg.eig(n_array)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)
# iv. Inverse
print("Inverse:\n", np.linalg.inv(n_array))
# v. Determinant
print("Determinant:", np.linalg.det(n_array))

Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [26]:
import numpy as np
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("Multiplication 1:\n", np.dot(p1, q1))
print("Covariance 1:\n", np.cov(np.hstack((p1, q1)).T))
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("Multiplication 2:\n", np.dot(p2, q2))
print("Covariance 2:\n", np.cov(np.hstack((p2, q2.T)).T))


Multiplication 1:
 [[16 19]
 [26 31]]
Covariance 1:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
Multiplication 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance 2:
 [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [15]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:\n", np.inner(x, y))
print("Outer product:\n", np.outer(x, y))
print("Cartesian product:\n", np.tensordot(x, y, axes=0))

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[[[ 2 10  0]
   [10 20  6]]

  [[ 3 15  0]
   [15 30  9]]

  [[ 4 20  0]
   [20 40 12]]]


 [[[ 3 15  0]
   [15 30  9]]

  [[ 2 10  0]
   [10 20  6]]

  [[ 9 45  0]
   [45 90 27]]]]


In [16]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
# i. Absolute
print("Absolute:\n", np.abs(array))
# ii. Percentiles
print("25th, 50th, 75th (flattened):", np.percentile(array, [25,50,75]))
print("Column-wise:\n", np.percentile(array, [25,50,75], axis=0))
print("Row-wise:\n", np.percentile(array, [25,50,75], axis=1))
# iii. Mean, Median, Std
print("Flattened -> Mean:", np.mean(array), "Median:", np.median(array), "Std:", np.std(array))
print("Column-wise -> Mean:", np.mean(array, axis=0))
print("Row-wise -> Mean:", np.mean(array, axis=1))


Absolute:
 [[1 2 3]
 [4 5 6]]
25th, 50th, 75th (flattened): [-3.5 -0.5  2.5]
Column-wise:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened -> Mean: -0.5 Median: -0.5 Std: 3.8622100754188224
Column-wise -> Mean: [-1.5  1.5 -1.5]
Row-wise -> Mean: [ 0.66666667 -1.66666667]


In [17]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Round:", np.round(a))


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


In [19]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:", np.sort(array))
print("Indices of sorted array:", np.argsort(array))
print("4 smallest:", np.sort(array)[:4])
print("5 largest:", np.sort(array)[-5:])


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]


In [20]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print("Integer elements:", integers)
print("Float elements:", floats)


Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


In [25]:
import numpy as np
from PIL import Image
path = "/content/RGB.jpg"
def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        print("Grayscale image detected.")
        np.savetxt("image_array.txt", arr, fmt='%d')
    else:   # RGB
        print("RGB image detected.")
        np.savetxt("image_array.txt", arr.reshape(-1, arr.shape[-1]), fmt='%d')
    print("Image saved as text file.")
img_to_array(path)
loaded = np.loadtxt("image_array.txt", dtype=int)
print("Loaded array:\n", loaded)


RGB image detected.
Image saved as text file.
Loaded array:
 [[241 187   1]
 [244 190   4]
 [255 207  24]
 ...
 [  5   3  40]
 [  5   3  40]
 [  5   3  40]]


ASSIGNMENT 2


a) The customer dataset contains several attributes, but not all are relevant for predicting whether a person will be a potential bike buyer. Attributes such as CustomerID, FirstName, LastName, AddressLine1, AddressLine2, PhoneNumber, and LastUpdated are identifiers or administrative details that do not contribute meaningful patterns for prediction and can therefore be removed.
Features selected are -- BirthDate, Education, Occupation, Gender, MaritalStatus, HomeOwnerFlag, NumberCarsOwned, NumberChildrenAtHome, TotalChildren, YearlyIncome, StateProvinceName, CountryRegionName

In [29]:
import pandas as pd
df = pd.read_csv("AWCustomers.csv")
selected_columns = [
"BirthDate", "Education", "Occupation", "Gender", "MaritalStatus",
    "HomeOwnerFlag", "NumberCarsOwned", "NumberChildrenAtHome",
    "TotalChildren", "YearlyIncome"
]

df_selected = df[selected_columns]

print(df_selected.head())

    BirthDate        Education      Occupation Gender MaritalStatus  \
0  1987-11-13        Bachelors        Clerical      M             M   
1  1972-07-21  Partial College        Clerical      M             M   
2  1985-11-09        Bachelors        Clerical      F             S   
3  1977-10-18  Partial College  Skilled Manual      M             M   
4  1975-02-05  Partial College  Skilled Manual      M             S   

   HomeOwnerFlag  NumberCarsOwned  NumberChildrenAtHome  TotalChildren  \
0              1                3                     0              1   
1              1                2                     1              2   
2              0                3                     0              0   
3              1                2                     1              2   
4              1                1                     0              0   

   YearlyIncome  
0         81916  
1         81076  
2         86387  
3         61481  
4         51804  


In [32]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import KBinsDiscretizer
customers = pd.read_csv("AWCustomers.csv")
sales = pd.read_csv("AWSales.csv")
df = sales.merge(customers, on="CustomerID", how="left")
print("Original shape:", df.shape)
num_imputer = SimpleImputer(strategy='median')
cat_imputer = SimpleImputer(strategy='most_frequent')
numeric_cols = df.select_dtypes(include=[np.number]).columns
categorical_cols = df.select_dtypes(exclude=[np.number]).columns
df[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])
scaler = MinMaxScaler()
df_normalized = df.copy()
df_normalized[numeric_cols] = scaler.fit_transform(df[numeric_cols])
bin_cols = ["YearlyIncome", "SalesAmount"]
for col in bin_cols:
    if col in df.columns:
        kb = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile')
        df_normalized[col + "_binned"] = kb.fit_transform(df[[col]])
std_scaler = StandardScaler()
df_standardized = df.copy()
df_standardized[numeric_cols] = std_scaler.fit_transform(df[numeric_cols])
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore", max_categories=20, drop="first")
encoded = encoder.fit_transform(df[categorical_cols])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(categorical_cols))
df_encoded = pd.concat([df[numeric_cols].reset_index(drop=True), encoded_df.reset_index(drop=True)], axis=1)
print("Normalized shape:", df_normalized.shape)
print("Standardized shape:", df_standardized.shape)
print("One-hot encoded shape:", df_encoded.shape)

Original shape: (18361, 26)
Normalized shape: (18361, 27)
Standardized shape: (18361, 26)
One-hot encoded shape: (18361, 218)


In [35]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
obj1 = df_encoded.iloc[0].values
obj2 = df_encoded.iloc[1].values
def simple_matching(x, y):
    return np.sum(x == y) / len(x)

def jaccard_similarity(x, y):
    intersection = np.sum((x == 1) & (y == 1))
    union = np.sum((x == 1) | (y == 1))
    return intersection / union if union != 0 else 0
cosine_sim = cosine_similarity([obj1], [obj2])[0][0]
print("Simple Matching:", simple_matching(obj1, obj2))
print("Jaccard Similarity:", jaccard_similarity(obj1, obj2))
print("Cosine Similarity:", cosine_sim)


Simple Matching: 0.9403669724770642
Jaccard Similarity: 0.5263157894736842
Cosine Similarity: 0.9958665768029795
